# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poiapp', '0002_auto_20170123_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
    ]
