# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poiapp', '0003_auto_20170123_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'story', 'verbose_name_plural': 'stories'},
        ),
        migrations.RemoveField(
            model_name='poi',
            name='genre',
        ),
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='poiapp.Genre'),
        ),
    ]
